Repository googleapis/java-video-intelligence, pull requests merged in 2020-06, with the labels that each got.

#170 test: fix integration tests
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/it/ITSystemTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta2/it/ITSystemTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/it/ITSystemTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/it/ITSystemTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/it/ITSystemTest.java
Labels: automerge, cla: yes

#173 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#175 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#179 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#184 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#191 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#193 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#199 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-video-intelligence/pom.xml
  grpc-google-cloud-video-intelligence-v1/pom.xml
  grpc-google-cloud-video-intelligence-v1beta2/pom.xml
  grpc-google-cloud-video-intelligence-v1p1beta1/pom.xml
  grpc-google-cloud-video-intelligence-v1p2beta1/pom.xml
  grpc-google-cloud-video-intelligence-v1p3beta1/pom.xml
  pom.xml
  proto-google-cloud-video-intelligence-v1/pom.xml
  proto-google-cloud-video-intelligence-v1beta2/pom.xml
  proto-google-cloud-video-intelligence-v1p1beta1/pom.xml
  proto-google-cloud-video-intelligence-v1p2beta1/pom.xml
  proto-google-cloud-video-intelligence-v1p3beta1/pom.xml
Labels: cla: yes

#198 fix: migrate to grpc_service_config
  README.md
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/StreamingVideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/VideoIntelligenceServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#210 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
