Repository googleapis/java-video-intelligence, pull requests merged in 2020-09, with the labels that each got.

#232 chore: regenerate README
  README.md
  synth.metadata
Labels: api: videointelligence, cla: yes, context: none

#239 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#253 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#255 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: videointelligence, automerge, cla: yes

#264 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#267 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
