Repository googleapis/java-video-intelligence, pull requests merged in 2020-12, with the labels that each got.

#347 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#344 samples: update person detection to GA
  samples/install-without-bom/pom.xml
  samples/snippets/src/main/java/video/Detect.java
  samples/snippets/src/main/java/video/DetectPerson.java
  samples/snippets/src/main/java/video/DetectPersonGcs.java
  samples/snippets/src/main/java/video/LogoDetection.java
  samples/snippets/src/main/java/video/LogoDetectionGcs.java
  samples/snippets/src/main/java/video/QuickstartSample.java
  samples/snippets/src/main/java/video/TextDetection.java
  samples/snippets/src/main/java/video/TrackObjects.java
  samples/snippets/src/test/java/video/DetectIT.java
  samples/snippets/src/test/java/video/DetectLogoGcsTest.java
  samples/snippets/src/test/java/video/DetectLogoTest.java
  samples/snippets/src/test/java/video/DetectPersonGcsIT.java
  samples/snippets/src/test/java/video/DetectPersonIT.java
  samples/snippets/src/test/java/video/DetectTextTest.java
  samples/snippets/src/test/java/video/QuickstartIT.java
  samples/snippets/src/test/java/video/Retry.java
Labels: api: videointelligence, cla: yes

#350 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#352 fix: incorrect and misleading attribute description for person detection samples
  samples/snippets/src/main/java/video/DetectPerson.java
  samples/snippets/src/main/java/video/DetectPersonGcs.java
Labels: api: videointelligence, cla: yes, samples

#354 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#358 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#364 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#365 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#366 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: videointelligence, cla: yes, context: full, merge
