Repository googleapis/java-video-intelligence, pull requests merged in 2021-06, with the labels that each got.

#543 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#545 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#549 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#548 chore: release gapic-generator-java v1.0.10
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoIntelligenceServiceClientTest.java
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#555 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#556 chore: release gapic-generator-java v1.0.11
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClientTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceClientTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoIntelligenceServiceClientTest.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceClientTest.java
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#562 chore: release gapic-generator-java v1.0.12
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/StreamingVideoIntelligenceServiceStubSettings.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/VideoIntelligenceServiceStubSettings.java
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#565 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#568 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#569 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#561 chore: added error message for capturing error
  samples/snippets/src/main/java/beta/video/StreamingShotChangeDetection.java
Labels: api: videointelligence, cla: yes

#570 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#571 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#575 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes
