Repository googleapis/java-video-intelligence, pull requests merged in 2021-02, with the labels that each got.

#388 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: videointelligence, cla: yes, context: partial

#390 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#391 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#396 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#395 docs: generate sample code in the Java microgenerator
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/package-info.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/package-info.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/package-info.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/package-info.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceClient.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/package-info.java
  samples/snippets/src/main/java/video/DetectPerson.java
  samples/snippets/src/main/java/video/DetectPersonGcs.java
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full, samples

#400 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#399 chore: update gapic-generator-java to 0.0.20
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/stub/GrpcVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/stub/GrpcVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/stub/GrpcVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/stub/GrpcVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/GrpcStreamingVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/GrpcVideoIntelligenceServiceStub.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/MockVideoIntelligenceServiceImpl.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta2/MockVideoIntelligenceServiceImpl.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/MockStreamingVideoIntelligenceServiceImpl.java
  google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/MockVideoIntelligenceServiceImpl.java
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#401 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#402 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#403 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#405 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/gapic_metadata.json
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/gapic_metadata.json
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/gapic_metadata.json
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/gapic_metadata.json
  google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/gapic_metadata.json
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#409 chore: removed wrong comment and updated according to python samples
  samples/snippets/src/main/java/beta/video/DetectFaces.java
  samples/snippets/src/main/java/beta/video/DetectFacesGcs.java
Labels: api: videointelligence, cla: yes, samples

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#413 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes
