Repository googleapis/java-video-intelligence, pull requests merged in 2021-05, with the labels that each got.

#498 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: none

#500 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#506 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#511 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#513 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#515 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#516 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#510 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#526 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#531 chore: increase timeouts for tracking objects samples
  samples/snippets/src/main/java/beta/video/TrackObjects.java
  samples/snippets/src/main/java/com/example/video/TrackObjects.java
  samples/snippets/src/main/java/video/TrackObjects.java
Labels: api: videointelligence, automerge, cla: yes, samples

#532 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#502 samples: add streaming_automl_object_tracking sample
  samples/snippets/src/main/java/beta/video/StreamingAutoMlObjectTracking.java
  samples/snippets/src/test/java/beta/video/StreamingAutoMlObjectTrackingIT.java
Labels: api: videointelligence, cla: yes, samples

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#538 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#539 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes
