Repository googleapis/java-video-intelligence, pull requests merged in 2021-04, with the labels that each got.

#449 samples: updates face and people to v1
  samples/snippets/src/main/java/com/example/video/Detect.java
  samples/snippets/src/main/java/video/DetectFaces.java
  samples/snippets/src/main/java/video/DetectFacesGcs.java
  samples/snippets/src/test/java/video/DetectFacesGcsIT.java
  samples/snippets/src/test/java/video/DetectFacesIT.java
Labels: api: videointelligence, cla: yes, samples

#451 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#454 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#457 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#456 chore: removed try/catch & added exceptions at method signature
  samples/snippets/src/main/java/beta/video/StreamingShotChangeDetection.java
  samples/snippets/src/test/java/beta/video/StreamingShotChangeDetectionIT.java
Labels: api: videointelligence, automerge, cla: yes

#465 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#468 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#470 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#472 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#464 chore: removed all catch clauses which were causing error stack trace…
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/beta/video/StreamingAnnotationToStorage.java
  samples/snippets/src/main/java/beta/video/StreamingAutoMlClassification.java
  samples/snippets/src/main/java/beta/video/StreamingExplicitContentDetection.java
  samples/snippets/src/main/java/beta/video/StreamingLabelDetection.java
  samples/snippets/src/main/java/beta/video/StreamingObjectTracking.java
  samples/snippets/src/test/java/beta/video/StreamingAnnotationToStorageIT.java
  samples/snippets/src/test/java/beta/video/StreamingExplicitContentDetectionIT.java
  samples/snippets/src/test/java/beta/video/StreamingLabelDetectionIT.java
  samples/snippets/src/test/java/beta/video/StreamingObjectTrackingIT.java
  samples/snippets/src/test/java/video/DetectTextTest.java
  samples/snippets/src/test/java/video/Retry.java
Labels: api: videointelligence, cla: yes

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes, kokoro:force-run

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes

#494 chore: migrate videointelligence to the PHP microgenerator
  proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/AnnotateVideoRequest.java
  proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/AnnotateVideoRequestOrBuilder.java
  proto-google-cloud-video-intelligence-v1beta2/src/main/proto/google/cloud/videointelligence/v1beta2/video_intelligence.proto
  proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/AnnotateVideoRequest.java
  proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/AnnotateVideoRequestOrBuilder.java
  proto-google-cloud-video-intelligence-v1p1beta1/src/main/proto/google/cloud/videointelligence/v1p1beta1/video_intelligence.proto
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full, kokoro:force-run

#496 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: videointelligence, automerge, cla: yes
