Repository googleapis/java-video-intelligence, pull requests merged in 2021-09, with the labels that each got.

#653 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: videointelligence, automerge, context: full

#670 chore(java): install maven 3.8.1 at runtime
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, api: videointelligence, context: full

#667 Feat: Add code sample for video streaming action recognition.
  samples/snippets/src/main/java/beta/video/StreamingAutoMlActionRecognition.java
  samples/snippets/src/test/java/beta/video/StreamingAutoMlActionRecognitionIT.java
Labels: cla: yes, api: videointelligence, automerge, samples

#693 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: videointelligence, automerge

#694 chore: remove readme synth.py
  .github/.OwlBot.lock.yaml
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
Labels: cla: yes, api: videointelligence

#685 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: videointelligence

#705 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: videointelligence, automerge
